#!/bin/bash

cd ~/repositories/devlegacy/ts-clean-architecture
# .bin/try_rabbit/queue_subscriber
npx tsnd --transpile-only -r tsconfig-paths/register -r ts-node/register/transpile-only ./src/Contexts/Shared/infrastructure/EventBus/RabbitMQ/demos/subscriber/fanout-exchange.ts
