version: '3.9'

networks:
  app-network:
    name: app-network
    driver: bridge
    ipam:
      driver: default

# Volúmenes gestionados por Docker
# volumes:
  # certs:
  #   driver: local
  # esdata:
  #   driver: local
  # eventstore-volume-data:
  # eventstore-volume-logs:
  # .data/mongo:
  # .data/postgres:
  # .data/pgadmin:
  # .data/redis:
  # .data/esdata:
  # .data/keycloak:

# docker-compose up -d
# user docker-compose -f docker-compose.yml -f docker-compose.mongo.yml -f docker-compose.rabbitmq.yml up -d
