version: '3.9'

services:
  mongo:
    image: mongo:latest # 5.0.0
    restart: always
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
      - MONGO_URL=mongodb://mongo:27017/dev
    ports:
      # HOST:CONTAINER
      - 27017:27017
    # Persistence
    volumes:
      - ./.data/mongo:/data/db:delegated

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: mooc # postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      # HOST:CONTAINER
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_LISTEN_ADDRESS: "[::]"
    ports:
      # HOST:CONTAINER
      # ${PGADMIN_PORT:-8080}
      - "8080:80"
    # volumes:
      # - ./.data/postgres:/var/lib/pgadmin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default

# docker-compose up -d
