version: '3.9'
services:
  eventstore.db:
    image: eventstore/eventstore:latest
    container_name: eventstore.db
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 1113:1113
      - 2113:2113
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    # esdb://eventstore.db:2113?tls=false
    # http://localhost:2113/
    networks:
      - app-network

  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:latest
    # image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:latest
    # image: confluentinc/cp-kafka:latest
    hostname: localhost
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
      - 29092:29092
    environment:
      - KAFKA_ENABLE_KRAFT=no
      # - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNALPLAINTEXT://:29092,CONTROLLER://:9093,EXTERNAL://:9094
      # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNALPLAINTEXT://localhost:29092,CONTROLLER://localhost:9093,EXTERNAL://localhost:9094
      # - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNALPLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=EXTERNALPLAINTEXT
      # - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_ADVERTISED_HOST_NAME=192.168.1.68
      # - KAFKA_AUTO_CREATE_TOPICS_ENABLE='true'
      # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    volumes:
      - ./.data/control-center:/var/lib/confluent-control-center
    networks:
      - app-network

  control-center:
    container_name: control-center
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    ports:
      - 9021:9021
    environment:
      - CONTROL_CENTER_REPLICATION_FACTOR=1
      - CONTROL_CENTER_ZOOKEEPER_CONNECT=zookeeper:2181
      - CONTROL_CENTER_BOOTSTRAP_SERVERS=kafka:9092
      - CONTROL_CENTER_CONNECT_CLUSTER=localhost:8083
    depends_on:
      - zookeeper
      - kafka
    networks:
      - app-network

  debezium:
    container_name: debezium
    image: debezium/connect:latest
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - BOOTSTRAP_SERVERS=kafka:9092
      - ADVERTISED_HOST_NAME=debezium
    ports:
      - 8083:8083
    depends_on:
      - kafka
    networks:
      - app-network

  redis:
    container_name: redis
    # image: redis:alpine
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    # command: [ "redis-server", "--requirepass", "SUPER_SECRET_PASSWORD" ]
    volumes:
      - ./.data/redis:/data
    environment:
      - REDIS_ARGS=--requirepass SUPER_SECRET_PASSWORD
    networks:
      - app-network
    # redis-cli --pass SUPER_SECRET_PASSWORD
    # JSON.GET blocks
    # [redis-cli] info tsyringe-dependency-injection --pass SUPER_SECRET_PASSWORD

  keycloak:
    container_name: keycloak
    # image: quay.io/keycloak/keycloak:latest
    image: quay.io/phasetwo/phasetwo-keycloak:latest
    # command: start
    command:
      - start-dev
      - --spi-event-listener-keycloak-custom-event-listener-enabled=true
      - --spi-event-listener-keycloak-custom-event-listener=keycloak-custom
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --features="preview,docker"
      # - -Dkeycloak.profile.feature.upload_scripts=enabled
      # - -Dkeycloak.profile.feature.docker=enabled
    volumes:
      # - ./.data/keycloak/themes:/opt/jboss/keycloak/themes
      # - ./.data/keycloak/config:/opt/jboss/keycloak/standalone/configuration
      - ./.data/keycloak:/opt/jboss/keycloak/standalone/data/
    ports:
      # HOST:CONTAINER
      - 8081:8080
      - 8082:8443
    restart: unless-stopped
    environment:
      # Credentials for admin account
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=DEBUG
      - KEYCLOAK_LOG_BOOTSTRAP=DEBUG
      - KEYCLOAK_LOG_JBAS=DEBUG
      # - ROOT_LOGLEVEL=DEBUG
      # Credentials for storing into an external database
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      # - KC_DB_URL_DATABASE=keycloak
      # - KC_DB_SCHEMA=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KAFKA_EVENTS_ENABLED=true
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=keycloak-events
      - KAFKA_EVENTS_LISTENERS=org.keycloak.services.event.listeners.AuditEventPersisterFactory
      - KEYCLOAK_EVENTS_ENABLED=true
    # logging:
    #   driver: journald # windows
    depends_on:
      - postgres
      # - kafka
    networks:
      - app-network
