version: '3.9'

services:

networks:
  app-network:
    name: app-network
    driver: bridge
    ipam:
      driver: default

# Volúmenes gestionados por Docker
# volumes:
  # certs:
  #   driver: local
  # esdata:
  #   driver: local
  # eventstore-volume-data:
  # eventstore-volume-logs:
  # .data/mongo:
  # .data/postgres:
  # .data/pgadmin:
  # .data/redis:
  # .data/esdata:
  # .data/keycloak:

# docker-compose up -d
# docker network create app-network --driver bridge
# user docker-compose -f docker-compose.yml up -d && docker-compose -f docker-compose.mongo.yml -f docker-compose.rabbitmq.yml -f docker-compose.elasticsearch.yml up -d

# user docker-compose -f docker-compose.yml -f docker-compose.mongo.yml -f docker-compose.rabbitmq.yml -f docker-compose.elasticsearch.yml up -d
