export const ONE_SECOND_IN_MILLISECONDS = 1_000
export const TWO_SECONDS_IN_MILLISECONDS = 2_000 // 2 * ONE_SECOND_IN_MILLISECONDS
export const ONE_MINUTE_IN_MILLISECONDS = 60_000 // 60 * ONE_SECOND_IN_MILLISECONDS
export const TEN_SECONDS_IN_MILLISECONDS = 10_000 // 2 * 5000// 10 * ONE_SECOND_IN_MILLISECONDS
export const ONE_DAY_IN_MILLISECONDS = 86_400_000 // 24 * ONE_HOUR_IN_MILLISECONDS

export const TWO_SECONDS = 2
export const TEN_SECONDS = 10
