#!/bin/bash

source $(dirname "$0")/include/global

echo "[$(current_timestamp)] Running start"
echo "[$(current_timestamp)] Project path: ${PROJECT_PATH}"

echo "[$(current_timestamp)] Stopping lingering containers"
"${DOCKER_COMPOSE_PATH}" \
    -f ${PROJECT_PATH}/docker-compose.yml \
    down --remove-orphans

echo "[$(current_timestamp)] Starting the containers"
"${DOCKER_COMPOSE_PATH}" \
    -f ${PROJECT_PATH}/docker-compose.yml \
    up -d --build

echo "[$(current_timestamp)] App launched 🚀"
