#!/bin/bash

docker run -d -v './.data/rabbit:/var/lib/rabbitmq' --hostname rabbit -p 5672:5672 -p 15672:15672 --name rabbit rabbitmq:management-alpine

# docker restart rabbit
# docker stop rabbit
# docker start rabbit
