name: Node CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [16.x,18.x] # current versions + next versions o prepare future migrations
        mongodb-version: ['6.0']

    steps:
      # https://github.com/actions/setup-node
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # https://github.com/supercharge/mongodb-github-action
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Start RabbitMQ
        uses: namoshek/rabbitmq-github-action@v1
        with:
          version: 'latest'
      - name: npm install
        run: |
          npm install
      - name: npm run build
        run: |
          npm run build --if-present
          npm run lint
      - name: npm test
        run: |
          npm test
